### ISSUE TITLE
Version comarison with alpha

### ISSUE THREAD

**Issue by tonaim** [masahiro331/go-mvn-version#6]
Version comparison with alpha not working.

leftVersion, err := mvnVersion.NewVersion("11.0.0-alpha1")
	if err == nil {
		rightVersion, err := mvnVersion.NewVersion("11.0.0.alpha0")
		if err == nil {
			fmt.Println(leftVersion.Compare(rightVersion))
		}
	}

OUTPUT:   -1

**Comment by masahiro331** [comment]
@tonaim 

This is maven comapare implement
```
# maven version comapare
$ java -jar  target/maven-artifact-4.0.0-alpha-1-SNAPSHOT.jar 11.0.0-alpha1 11.0.0.alpha0
Display parameters as parsed by Maven (in canonical form and as a list of tokens) and comparison result:
1. 11.0.0-alpha1 -> 11-alpha-1; tokens: [11, [alpha, [1]]]
   11.0.0-alpha1 < 11.0.0.alpha0
2. 11.0.0.alpha0 -> 11.0.0.alpha; tokens: [11, 0, 0, alpha]
```
